### ISSUE TITLE
Implement Currency conversion

### ISSUE THREAD

**Issue by recrsn** [agathver/ec2pricing#2]
It would be very beneficial if the currency in USD may be converted to other currencies, like INR

**Comment by seraco** [comment]
I'll work on that! 😃

**Comment by himanisilky** [comment]
Currency shows sign/symbol before the amount itself.

**Comment by recrsn** [comment]
Ideally, we could just place a drop-down on the top to select the current currency and format the values in table accordingly.

@himanisilky 
> Currency shows sign/symbol before the amount itself.

Yes like $12.0021 or ₹22,5

**Comment by seraco** [comment]
I have finished now with the conversion of currency and created a pull request! 😀
